title: Wellpro
default_lang: en
author:
  name: 'Stephanie Niazi'
  email: joe@test.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Well Pro Dubai Blog'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
